apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: apps.app.o0w0o.cn
spec:
  group: app.o0w0o.cn
  names:
    kind: App
    plural: apps
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            microServices:
              items:
                properties:
                  name:
                    type: string
                  spec:
                    properties:
                      currentVersionName:
                        type: string
                      loadBalance:
                        properties:
                          ingress:
                            properties:
                              name:
                                type: string
                              spec:
                                type: object
                            required:
                            - name
                            - spec
                            type: object
                          service:
                            properties:
                              name:
                                type: string
                              spec:
                                type: object
                            required:
                            - name
                            - spec
                            type: object
                        type: object
                      versions:
                        items:
                          properties:
                            canary:
                              properties:
                                canaryIngressName:
                                  type: string
                                cookie:
                                  type: string
                                header:
                                  type: string
                                headerValue:
                                  type: string
                                weight:
                                  format: int64
                                  maximum: 100
                                  minimum: 1
                                  type: integer
                              required:
                              - weight
                              type: object
                            name:
                              type: string
                            serviceName:
                              type: string
                            template:
                              type: object
                          required:
                          - name
                          - template
                          type: object
                        type: array
                    required:
                    - versions
                    - currentVersionName
                    type: object
                required:
                - name
                type: object
              type: array
          type: object
        status:
          properties:
            availableVersions:
              format: int32
              type: integer
            conditions:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of deployment condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            totalVersions:
              format: int32
              type: integer
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
