apiVersion: app.o0w0o.cn/v1
kind: MicroService
metadata:
  name: voting-web
spec:
  loadBalance:
    service:
      name: voting-web
      spec:
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
    ingress:
      name: voting-web
      spec:
        rules:
          - host: voting.o0w0o.cn
            http:
              paths:
                - path: /bar
                  backend:
                    serviceName: voting-web
                    servicePort: 80
  versions:
    - name: v1
      template:
        replicas: 2
        selector:
          matchLabels:
            app: voting-web
        template:
          metadata:
            labels:
              app: voting-web
          spec:
            containers:
              - image: daocloud.io/w0v0w/voting-demo-voting:v1
                name: voting-web
    - name: v2
      canary:
        weight: 10
      template:
        replicas: 1
        selector:
          matchLabels:
            app: voting-web-for-kid
        template:
          metadata:
            labels:
              app: voting-web-for-kid
          spec:
            containers:
              - image: daocloud.io/w0v0w/voting-demo-voting:v2
                name: voting-web-for-kid
  currentVersionName: v1
